theme = "native"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;K}"
clickable = true
on_click = "squeekboard"

[[block]]
block = "cpu"
interval = 1
format = "{boost}{barchart}{utilization}"

[[block]]
block = "sound"
format = "{volume}"
on_click = "pavucontrol"

[[block]]
block = "custom"
command = ''' cat /sys/class/backlight/intel_backlight/brightness | awk '{printf("%d\n",$1/512*100+0.5)}' '''
interval = 0.4
signal = 4

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}"

#[[block]]
#block = "networkmanager"
#on_click = "alacritty -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#interface_name_include = []

[[block]]
block = "net"
interval = 5
on_click = "alacritty -e nmtui"
[block.format]
full = "{ssid} {signal_strength} {speed_down;K*b} {graph_down:8;M*_b#50}"
short = "{ssid}"


#[[block]]
#block = "kdeconnect"
#format = "10T {bat_icon}{bat_charge} {notif_icon}{notif_count}"
#bat_critical = 5
#bat_warning = 15
#bat_good = 60
#bat_info = 60

[[block]]
block = "custom"
command = ''' cat /sys/class/thermal/thermal_zone0/temp | awk '{printf("%.1f\n",$1/1000)}' '''
interval = 1

[[block]]
block = "battery"
format = "{percentage} {power}"
full_threshold = 100
full_format = "{percentage} {power}"
warning = 15
critical = 5
interval = 1
#[[block]]
#block = "toggle"
#text = "Battery Level:"
#command_state = ""
#command_on = "echo 100 > /sys/class/power_supply/BAT0/charge_control_end_threshold"
#command_off = "echo 60 > /sys/class/power_supply/BAT0/charge_control_end_threshold"
#interval = 5


[[block]]
block = "time"
interval = 1
format = "%Y-%m-%d|%H:%M:%S"
